call dein#add('kchmck/vim-coffee-script', { 'on_ft': 'coffee' })
call dein#add('pangloss/vim-javascript', { 'on_ft': 'js' })
call dein#add('mxw/vim-jsx', { 'on_ft': 'jsx' })
call dein#add('Quramy/tsuquyomi', { 'on_ft': 'typescript' })
call dein#add('leafgarland/typescript-vim', { 'on_ft': 'typescript' })
